name: Merge
on: [push]
jobs:
  main:
    name: Merge Mergely
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: perform merge
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git pull
          git checkout "mergely"
          git status
          git checkout "$GITHUB_HEAD_REF"
          git merge "mergely" --no-edit
          git push
          git status